"""Add is_verified in Article

Revision ID: 2fd2bf3bd37a
Revises: 318ebd3d0894
Create Date: 2021-03-24 18:56:52.066611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fd2bf3bd37a'
down_revision = '318ebd3d0894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'is_verified')
    # ### end Alembic commands ###
